export const TEXT_AREA_MAX = 5000;
export const TEXT_INPUT_MAX = 150;
export const EMAIL_MAX = 320;
export const SEARCH_FIELD_PATTERN = '^(?!.*[<>]).*'; //Allow everything but < and >
export const IDENTIFIER_MAX = 120;
export const MODEL_PREFIX_MAX = 32;
export const DEFAULT_START_PAGE = 1;
export const PAGE_SIZE_SMALL = 20;
export const PAGE_SIZE_LARGE = 50;
